export default {
  row: 'Row',
  searchByTitle: 'Search by title',
  searchByGenre: 'Search by genre',
  cinema: 'Cinema',
  action: 'Action',
  adventures: 'Adventures',
  comedy: 'Comedy',
  drama: 'Drama',
  horror: 'Horror',
  westerns: 'Westerns',
  main: 'Main',
  sessionSchedule: 'Session schedule',
  ticket: 'Ticket',
  chooseSeat: 'Choose seat',
  screen: 'Screen',
  seat: 'Seat',
  book: 'Book',
  booking: 'Booking',
  title: 'Title',
  date: 'Date',
  time: 'Time',
  continue: 'Continue',
  ticketBooked: 'Ticket booked successfully',
  homePage: 'Home page',
  pageNotFound: '404 Not Found',
  otherError: 'An error occurred',
  notFound: 'Not found',
  bookError: 'Book error',
  seatTaken: 'Seat is taken',
}
