export default {
  row: 'Ряд',
  searchByTitle: 'Искать по названию',
  searchByGenre: 'Искать по жанру',
  cinema: 'Кинотеатр',
  action: 'Экшн',
  adventures: 'Приключения',
  comedy: 'Комедия',
  drama: 'Драма',
  horror: 'Ужасы',
  westerns: 'Вестерны',
  main: 'Главная',
  sessionSchedule: 'Расписание сеансов',
  ticket: 'Билет',
  chooseSeat: 'Выберите место',
  screen: 'Экран',
  seat: 'Место',
  book: 'Забронировать',
  booking: 'Бронирование',
  title: 'Название',
  date: 'Дата',
  time: 'Время',
  continue: 'Продолжить',
  ticketBooked: 'Билет успешно забронирован',
  homePage: 'Главная страница',
  pageNotFound: '404 Не Найдено',
  otherError: 'Произошла ошибка',
  notFound: 'Не найдено',
  bookError: 'Ошибка бронирования',
  seatTaken: 'Место занято',
}
